#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division

import sys

from numpy import *  # noqa
import scikits.audiolab as al

import pyaudio

import rospy
from rabbit_msgs.msg import Spectrum

from hark_msgs.msg import HarkFFT


if __name__ == '__main__':
    rospy.init_node("h2r_spectrum", anonymous=True)

    spec_pub = rospy.Publisher("spectrum", Spectrum, queue_size=100)

    spec_msg = Spectrum()
    def callback(hark_fft_msg):
        spec_msg.header = hark_fft_msg.header
        spec_msg.nch = hark_fft_msg.nch
        spec_msg.nfreq = hark_fft_msg.length

        data = zeros([spec_msg.nch, spec_msg.nfreq, 2])
        for m in range(hark_fft_msg.nch):
            data[m, :, 0] = array(hark_fft_msg.src[m].fftdata_real)
            data[m, :, 1] = array(hark_fft_msg.src[m].fftdata_imag)

        data.resize([data.size])
        spec_msg.data = data

        spec_pub.publish(spec_msg)
        
    hark_fft_sub = rospy.Subscriber("hark_fft", HarkFFT, callback, queue_size=100)

    rospy.spin()
