#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division

import sys

from numpy import *  # noqa
import scikits.audiolab as al

import pyaudio

import rospy
from rabbit_msgs.msg import Audio


if __name__ == '__main__':
    rospy.init_node("audio_playback")

    n_step = rospy.get_param("~n_step", 160)
    n_frame = rospy.get_param("~n_frame", 512)
    fname = rospy.get_param("~fname", "")
    gain = rospy.get_param("~gain", 20)
    ch = rospy.get_param("~ch", 0)

    rospy.loginfo("Step length: %d" % n_step)
    rospy.loginfo("Frame length: %d" % n_frame)
    rospy.loginfo("Wave file name: %s" % fname)

    pa = pyaudio.PyAudio()

    # open stream (2)
    print pa.get_device_count()
    stream = pa.open(format=pyaudio.paFloat32, channels=1, rate=16000, output=True,
                     frames_per_buffer=n_step*100, 
                     input_device_index=9)

    def callback(data):
        wav = array(data.data).reshape([data.len, data.nch])[:n_step, ch] * gain

        stream.write(wav.astype(float32).tostring())
        
    audio_sub = rospy.Subscriber("audio", Audio, callback, queue_size=500)

    rospy.spin()
    stream.stop_stream()
    stream.close()
    pa.close()
