#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division

import sys

from numpy import *  # noqa
import scikits.audiolab as al

import pyaudio

import rospy
from rabbit_msgs.msg import Audio


if __name__ == '__main__':
    rospy.init_node("wav_saver")

    n_step = rospy.get_param("~n_step", 160)
    n_frame = rospy.get_param("~n_frame", 512)
    fname = rospy.get_param("~fname", "")
    gain = rospy.get_param("~gain", 20)

    rospy.loginfo("Step length: %d" % n_step)
    rospy.loginfo("Frame length: %d" % n_frame)
    rospy.loginfo("Wave file name: %s" % fname)


    def callback(data):
        if callback.wav is None:
            callback.wav = zeros([1, data.nch])
        callback.wav = r_[callback.wav, array(data.data).reshape([data.len, data.nch])[:n_step]]
    callback.wav = None
        
    audio_sub = rospy.Subscriber("audio", Audio, callback, queue_size=500)

    rospy.spin()

    al.wavwrite(callback.wav, sys.argv[1], fs=16000, enc="pcm24")
